### ISSUE TITLE
predict.py run time error

### ISSUE THREAD

**Issue by kienchen** [gasparian/CRNN_OCR_lite#1]
run  predict.py 
without option of --validate
python3 predict.py --G 0 --model_path /data/data/CRNN_OCR_keras/data/OCR_IAM_ver1 \
--image_path /data/data/CRNN_OCR_keras/data/IAM_processed \
 --num_instances 128
 
has three errors
1) not found: set_offset_monochrome
2) not found: padd
3) img = cv2.cvtColor(img.astype(np.uint8), cv2.COLOR_BGR2GRAY)

AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by gasparian** [comment]
Hi!
I'm making refactoring right now, so I think it will be a small description and some example results in ~ 3-5 days. So it all will work soon ;)

**Comment by kienchen** [comment]
Many thanks for your reply!
