### ISSUE TITLE
sharing coreMl 

### ISSUE THREAD

**Issue by un-lock-me** [gasparian/CRNN_OCR_lite#2]
Hello,

Thanks for sharing your code, I have run your code I was wondering do you have Coreml model so we can run it on ios?
I tried to convert but as you have BilinearInterpolation layer, it complains that it is unknown.
Do you have any idea how could I convert it or if you have the coreml model do you mind to share it?

thanks,

**Comment by gasparian** [comment]
Hey, @saria85 ! Thanks for your feedback :)
I haven't converted this model with CoreML yet... And I would say, that besides `BilinearInterpolation` layer, we must convert or re-implement on Swift beam-search module (decoder).   
Generally, for custom layers, It needs to be passed some conversion function into `custom_conversion_functions` argument of convertor ([example](https://machinethink.net/blog/coreml-custom-layers/)).   
As part of my pet-project, I want to implement detector for handwriting text, and segmentation model for text binarizing.   
After it all will form solid pipeline - I'll start to make convertor for mobile devices... if somebody don't do it before, of course ;)
