### ISSUE TITLE
Predict.py runtime error 

### ISSUE THREAD

**Issue by sirison** [gasparian/CRNN_OCR_lite#3]
getting below error while running the code.

Using TensorFlow backend.
Traceback (most recent call last):
  File "predict.py", line 82, in <module>
    from utils import init_predictor, DecodeCTCPred, Readf, edit_distance, normalized_edit_distance, \
  File "C:\E_Drive\Data Science\Projects\529 Payments\codes\CRNN_OCR_lite\utils.py", line 16, in <module>
    from keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, add, \
ImportError: cannot import name 'ReLU'

**Comment by gasparian** [comment]
Hi, @sirison ! You can fix it in several ways:
1. Use prepared docker image, just pull it, like said in readme.
2. If you're using old version of keras, you can replace `ReLU(6.)` with `K.relu(x, max_value=6)`.
3. Or just update keras to `2.2.2` :) 
Hope it helps!

**Comment by sirison** [comment]
thank you !!! it worked ..
